name: Run test

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - run: npm i -g meteor
      - run: export PATH=/home/runner/.meteor:$PATH
      - run: npm ci
      - run: npm run test
