name: Run test

on:
  push:
    branches: [main, develop]

jobs:
  Test-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Setup Meteor.js environment
        uses: meteorengineer/setup-meteor@v1.0.8
      - run: meteor npm i
      - run: meteor npm test
