name: Deployment

on:
  push:
    branches: [main, develop]

jobs:
  # Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout branch
  #       uses: actions/checkout@v2

  #     - name: Setup Node for testing
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: "14.x"

  #     - name: Setup Meteor.js environment
  #       uses: meteorengineer/setup-meteor@v1.0.8
  #     - run: meteor npm i
  #     - run: meteor npm test

  Deployment:
    runs-on: ubuntu-latest
    # needs: Test
    env:
      PRIVATE_KEY: ${{ secrets.KEY  }}
      HOST : ${{ secrets.HOST  }}
      USERNAME : ${{ secrets.USERNAME  }}

    steps:
      - name: Prepare Project Files
        uses: actions/checkout@v2

      - name: Copy Files via ssh
        run: mkdir ~/.ssh
      - run: |
          echo "$PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
      - run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/private_key
          rsync -avz -e "ssh -o StrictHostKeyCHecking=no -o UserKnownHostsFile=/dev/null" --progress . ${USERNAME}@${HOST}:/home/${USERNAME}/srv/changeplan
          
      - name: Run project
        run: |
          ssh -i ~/.ssh/private_key ${USERNAME}@${HOST} '
          cd srv/changeplan
          npm i
          meteor run
          '      
