name: Deployment

on:
  push:
    branches: [main, develop]

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Setup Meteor.js environment
        uses: meteorengineer/setup-meteor@v1.0.8
      - run: ls -la
      - run: meteor npm i
      - run: meteor npm test

  Deployment:
    runs-on: ubuntu-latest
    needs: Test
    env:
      PRIVATE_KEY: ${{ secrets.KEY  }}
      HOST : ${{ secrets.HOST  }}
      USERNAME : ${{ secrets.USERNAME  }}

    steps:
      - name: Set up SSH Key
        run: node --version
      - run: ls -la
      - run: echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      - run: rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress . ${USERNAME}@${HOST}:/home/${USERNAME}/srv/
      - run: ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOST} '

          npm ci
          meteor run

          '
